/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author guinh
 */
public class Funcionarios extends javax.swing.JFrame {

    /**
     * Creates new form Funcionarios
     */
    public Funcionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuClienteAdicionar = new javax.swing.JMenuItem();
        menuClienteAtualizar = new javax.swing.JMenuItem();
        menuClienteDeletar = new javax.swing.JMenuItem();
        menuClienteConsultar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuPedidoAdicionar = new javax.swing.JMenuItem();
        menuPedidoAtualizar = new javax.swing.JMenuItem();
        menuPedidoConsultar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user.png"))); // NOI18N
        jMenu1.setText("Cliente");

        menuClienteAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_add.png"))); // NOI18N
        menuClienteAdicionar.setText("Adicionar");
        menuClienteAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteAdicionarActionPerformed(evt);
            }
        });
        jMenu1.add(menuClienteAdicionar);

        menuClienteAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_edit.png"))); // NOI18N
        menuClienteAtualizar.setText("Atualizar");
        menuClienteAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteAtualizarActionPerformed(evt);
            }
        });
        jMenu1.add(menuClienteAtualizar);

        menuClienteDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_delete.png"))); // NOI18N
        menuClienteDeletar.setText("Deletar");
        menuClienteDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteDeletarActionPerformed(evt);
            }
        });
        jMenu1.add(menuClienteDeletar);

        menuClienteConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/zoom.png"))); // NOI18N
        menuClienteConsultar.setText("Consultar");
        jMenu1.add(menuClienteConsultar);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/page.png"))); // NOI18N
        jMenu2.setText("Pedido");

        menuPedidoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/page_add.png"))); // NOI18N
        menuPedidoAdicionar.setText("Adicionar");
        menuPedidoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidoAdicionarActionPerformed(evt);
            }
        });
        jMenu2.add(menuPedidoAdicionar);

        menuPedidoAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/page_edit.png"))); // NOI18N
        menuPedidoAtualizar.setText("Atualizar");
        jMenu2.add(menuPedidoAtualizar);

        menuPedidoConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/zoom.png"))); // NOI18N
        menuPedidoConsultar.setText("Consultar");
        jMenu2.add(menuPedidoConsultar);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_suit.png"))); // NOI18N
        jMenu3.setText("Bater Ponto");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuClienteDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteDeletarActionPerformed
        
        DeletarCliente del = new DeletarCliente();
        jDesktopPane1.add(del);
        del.setVisible(true);
    }//GEN-LAST:event_menuClienteDeletarActionPerformed

    private void menuClienteAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteAdicionarActionPerformed
        
        AdicionarCLiente cad = new AdicionarCLiente();
        jDesktopPane1.add(cad);
        cad.setVisible(true);
    }//GEN-LAST:event_menuClienteAdicionarActionPerformed

    private void menuClienteAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteAtualizarActionPerformed
      
        AtualizarCliente atu = new AtualizarCliente();
        jDesktopPane1.add(atu);
        atu.setVisible(true);
    }//GEN-LAST:event_menuClienteAtualizarActionPerformed

    private void menuPedidoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidoAdicionarActionPerformed
        
        AdicionarPedido adc = new AdicionarPedido();
        jDesktopPane1.add(adc);
        adc.setVisible(true);
    }//GEN-LAST:event_menuPedidoAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuClienteAdicionar;
    private javax.swing.JMenuItem menuClienteAtualizar;
    private javax.swing.JMenuItem menuClienteConsultar;
    private javax.swing.JMenuItem menuClienteDeletar;
    private javax.swing.JMenuItem menuPedidoAdicionar;
    private javax.swing.JMenuItem menuPedidoAtualizar;
    private javax.swing.JMenuItem menuPedidoConsultar;
    // End of variables declaration//GEN-END:variables
}
