/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author guinh
 */
public class Gerentes extends javax.swing.JFrame {

    /**
     * Creates new form Gerentes
     */
    public Gerentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        menuClientesAdicionar = new javax.swing.JMenuItem();
        menuClientesAtualizar = new javax.swing.JMenuItem();
        menuClientesDeletar = new javax.swing.JMenuItem();
        menuClientesConsultar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuPedidosAdicionar = new javax.swing.JMenuItem();
        menuPedidosAtualizar = new javax.swing.JMenuItem();
        menuPedidosDeletar = new javax.swing.JMenuItem();
        menuPedidosConsultar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user.png"))); // NOI18N
        menuClientes.setText("Clientes");

        menuClientesAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_add.png"))); // NOI18N
        menuClientesAdicionar.setText("Adicionar");
        menuClientesAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesAdicionarActionPerformed(evt);
            }
        });
        menuClientes.add(menuClientesAdicionar);

        menuClientesAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_edit.png"))); // NOI18N
        menuClientesAtualizar.setText("Atualizar");
        menuClientesAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesAtualizarActionPerformed(evt);
            }
        });
        menuClientes.add(menuClientesAtualizar);

        menuClientesDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_delete.png"))); // NOI18N
        menuClientesDeletar.setText("Deletar");
        menuClientesDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesDeletarActionPerformed(evt);
            }
        });
        menuClientes.add(menuClientesDeletar);

        menuClientesConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/zoom.png"))); // NOI18N
        menuClientesConsultar.setText("Consultar");
        menuClientesConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesConsultarActionPerformed(evt);
            }
        });
        menuClientes.add(menuClientesConsultar);

        jMenuBar1.add(menuClientes);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/page.png"))); // NOI18N
        jMenu2.setText("Pedidos");

        menuPedidosAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/page_add.png"))); // NOI18N
        menuPedidosAdicionar.setText("Adicionar");
        menuPedidosAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidosAdicionarActionPerformed(evt);
            }
        });
        jMenu2.add(menuPedidosAdicionar);

        menuPedidosAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/page_edit.png"))); // NOI18N
        menuPedidosAtualizar.setText("Atualizar");
        jMenu2.add(menuPedidosAtualizar);

        menuPedidosDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/page_delete.png"))); // NOI18N
        menuPedidosDeletar.setText("Deletar");
        menuPedidosDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidosDeletarActionPerformed(evt);
            }
        });
        jMenu2.add(menuPedidosDeletar);

        menuPedidosConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/zoom.png"))); // NOI18N
        menuPedidosConsultar.setText("Consultar");
        jMenu2.add(menuPedidosConsultar);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/group.png"))); // NOI18N
        jMenu3.setText("Funcionarios");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/clock.png"))); // NOI18N
        jMenuItem9.setText("Horarios");
        jMenu3.add(jMenuItem9);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/building.png"))); // NOI18N
        jMenuItem11.setText("Departamentos");
        jMenu3.add(jMenuItem11);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_add.png"))); // NOI18N
        jMenuItem1.setText("Adicionar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_delete.png"))); // NOI18N
        jMenuItem2.setText("Deletar");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_edit.png"))); // NOI18N
        jMenuItem3.setText("Atualizar");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/zoom.png"))); // NOI18N
        jMenuItem4.setText("Consultar");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/package.png"))); // NOI18N
        jMenu4.setText("Entregas");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/package.png"))); // NOI18N
        jMenuItem12.setText("Entregas");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/money.png"))); // NOI18N
        jMenu5.setText("Caixa");

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/money.png"))); // NOI18N
        jMenuItem10.setText("Caixa");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
            Entregas ent = new Entregas();
            jDesktopPane1.add(ent);
            ent.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void menuClientesAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesAdicionarActionPerformed
            CadastroCliente cad = new CadastroCliente();
            jDesktopPane1.add(cad);
            cad.setVisible(true);
    }//GEN-LAST:event_menuClientesAdicionarActionPerformed

    private void menuClientesAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesAtualizarActionPerformed
            AtualizarCliente atu = new AtualizarCliente();
            jDesktopPane1.add(atu);
            atu.setVisible(true);
    }//GEN-LAST:event_menuClientesAtualizarActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void menuPedidosDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidosDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPedidosDeletarActionPerformed

    private void menuClientesDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesDeletarActionPerformed
        DeletarCliente del = new DeletarCliente();
        jDesktopPane1.add(del);
        del.setVisible(true);
    }//GEN-LAST:event_menuClientesDeletarActionPerformed

    private void menuClientesConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuClientesConsultarActionPerformed

    private void menuPedidosAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidosAdicionarActionPerformed
        AdicionarPedido adc = new AdicionarPedido();
        jDesktopPane1.add(adc);
        adc.setVisible(true);
    }//GEN-LAST:event_menuPedidosAdicionarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AdicionarFuncionario adcFun = new AdicionarFuncionario();
        jDesktopPane1.add(adcFun);
        adcFun.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gerentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenuItem menuClientesAdicionar;
    private javax.swing.JMenuItem menuClientesAtualizar;
    private javax.swing.JMenuItem menuClientesConsultar;
    private javax.swing.JMenuItem menuClientesDeletar;
    private javax.swing.JMenuItem menuPedidosAdicionar;
    private javax.swing.JMenuItem menuPedidosAtualizar;
    private javax.swing.JMenuItem menuPedidosConsultar;
    private javax.swing.JMenuItem menuPedidosDeletar;
    // End of variables declaration//GEN-END:variables
}
