
import ToPunchTela.AdicionarProduto;
import ToPunchTela.AtualizarFuncionario;
import ToPunchTela.Caixa;
import ToPunchTela.ConsultarCliente;
import ToPunchTela.ConsultarFuncionario;
import ToPunchTela.ConsultarProduto;
import ToPunchTela.DeletarFuncionario;
import ToPunchTela.DeletarProduto;
import ToPunchTela.Departamentos;
import ToPunchTela.Horarios;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author guinh
 */
public class Gerentes extends javax.swing.JFrame {

    /**
     * Creates new form Gerentes
     */
    public Gerentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        menuClientesAdicionar = new javax.swing.JMenuItem();
        menuClientesAtualizar = new javax.swing.JMenuItem();
        menuClientesDeletar = new javax.swing.JMenuItem();
        menuClientesConsultar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuPedidosAdicionar = new javax.swing.JMenuItem();
        menuPedidosAtualizar = new javax.swing.JMenuItem();
        menuPedidosDeletar = new javax.swing.JMenuItem();
        menuPedidosConsultar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuHorarios = new javax.swing.JMenuItem();
        menuDpt = new javax.swing.JMenuItem();
        menuFuncionariosAdd = new javax.swing.JMenuItem();
        menuFuncionariosDelete = new javax.swing.JMenuItem();
        menuFuncionarioUpdate = new javax.swing.JMenuItem();
        menuFuncionariosSearch = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuEntrega = new javax.swing.JMenuItem();
        AdicionarProd = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        JCaixa = new javax.swing.JMenu();
        menuCaixa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user.png"))); // NOI18N
        menuClientes.setText("Clientes");

        menuClientesAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_add.png"))); // NOI18N
        menuClientesAdicionar.setText("Adicionar");
        menuClientesAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesAdicionarActionPerformed(evt);
            }
        });
        menuClientes.add(menuClientesAdicionar);

        menuClientesAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_edit.png"))); // NOI18N
        menuClientesAtualizar.setText("Atualizar");
        menuClientesAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesAtualizarActionPerformed(evt);
            }
        });
        menuClientes.add(menuClientesAtualizar);

        menuClientesDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_delete.png"))); // NOI18N
        menuClientesDeletar.setText("Deletar");
        menuClientesDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesDeletarActionPerformed(evt);
            }
        });
        menuClientes.add(menuClientesDeletar);

        menuClientesConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/zoom.png"))); // NOI18N
        menuClientesConsultar.setText("Consultar");
        menuClientesConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesConsultarActionPerformed(evt);
            }
        });
        menuClientes.add(menuClientesConsultar);

        jMenuBar1.add(menuClientes);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/page.png"))); // NOI18N
        jMenu2.setText("Pedidos");

        menuPedidosAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/page_add.png"))); // NOI18N
        menuPedidosAdicionar.setText("Adicionar");
        menuPedidosAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidosAdicionarActionPerformed(evt);
            }
        });
        jMenu2.add(menuPedidosAdicionar);

        menuPedidosAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/page_edit.png"))); // NOI18N
        menuPedidosAtualizar.setText("Atualizar");
        menuPedidosAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidosAtualizarActionPerformed(evt);
            }
        });
        jMenu2.add(menuPedidosAtualizar);

        menuPedidosDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/page_delete.png"))); // NOI18N
        menuPedidosDeletar.setText("Deletar");
        menuPedidosDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedidosDeletarActionPerformed(evt);
            }
        });
        jMenu2.add(menuPedidosDeletar);

        menuPedidosConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/zoom.png"))); // NOI18N
        menuPedidosConsultar.setText("Consultar");
        jMenu2.add(menuPedidosConsultar);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/group.png"))); // NOI18N
        jMenu3.setText("Funcionarios");

        menuHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/clock.png"))); // NOI18N
        menuHorarios.setText("Horarios");
        menuHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHorariosActionPerformed(evt);
            }
        });
        jMenu3.add(menuHorarios);

        menuDpt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/building.png"))); // NOI18N
        menuDpt.setText("Departamentos");
        menuDpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDptActionPerformed(evt);
            }
        });
        jMenu3.add(menuDpt);

        menuFuncionariosAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_add.png"))); // NOI18N
        menuFuncionariosAdd.setText("Adicionar");
        menuFuncionariosAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionariosAddActionPerformed(evt);
            }
        });
        jMenu3.add(menuFuncionariosAdd);

        menuFuncionariosDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_delete.png"))); // NOI18N
        menuFuncionariosDelete.setText("Deletar");
        menuFuncionariosDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionariosDeleteActionPerformed(evt);
            }
        });
        jMenu3.add(menuFuncionariosDelete);

        menuFuncionarioUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_edit.png"))); // NOI18N
        menuFuncionarioUpdate.setText("Atualizar");
        menuFuncionarioUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionarioUpdateActionPerformed(evt);
            }
        });
        jMenu3.add(menuFuncionarioUpdate);

        menuFuncionariosSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/zoom.png"))); // NOI18N
        menuFuncionariosSearch.setText("Consultar");
        menuFuncionariosSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionariosSearchActionPerformed(evt);
            }
        });
        jMenu3.add(menuFuncionariosSearch);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/package.png"))); // NOI18N
        jMenu4.setText("Produtos");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        menuEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/package.png"))); // NOI18N
        menuEntrega.setText("Entregas");
        menuEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntregaActionPerformed(evt);
            }
        });
        jMenu4.add(menuEntrega);

        AdicionarProd.setText("Adicionar");
        AdicionarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarProdActionPerformed(evt);
            }
        });
        jMenu4.add(AdicionarProd);

        jMenuItem1.setText("Consultar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Remover");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Atualizar");
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        JCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/money.png"))); // NOI18N
        JCaixa.setText("Caixa");

        menuCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/money.png"))); // NOI18N
        menuCaixa.setText("Caixa");
        menuCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCaixaActionPerformed(evt);
            }
        });
        JCaixa.add(menuCaixa);

        jMenuBar1.add(JCaixa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void menuEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntregaActionPerformed
            Entregas ent = new Entregas();
            jDesktopPane1.add(ent);
            ent.setVisible(true);
    }//GEN-LAST:event_menuEntregaActionPerformed

    private void menuClientesAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesAdicionarActionPerformed
            AdicionarCLiente cad = new AdicionarCLiente();
            jDesktopPane1.add(cad);
            cad.setVisible(true);
    }//GEN-LAST:event_menuClientesAdicionarActionPerformed

    private void menuClientesAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesAtualizarActionPerformed
            AtualizarCliente atu = new AtualizarCliente();
            jDesktopPane1.add(atu);
            atu.setVisible(true);
    }//GEN-LAST:event_menuClientesAtualizarActionPerformed

    private void menuPedidosDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidosDeletarActionPerformed
        DeletarCliente delCli = new DeletarCliente();
        jDesktopPane1.add(delCli);
        delCli.setVisible(true);
    }//GEN-LAST:event_menuPedidosDeletarActionPerformed

    private void menuClientesDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesDeletarActionPerformed
        DeletarCliente del = new DeletarCliente();
        jDesktopPane1.add(del);
        del.setVisible(true);
    }//GEN-LAST:event_menuClientesDeletarActionPerformed

    private void menuClientesConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesConsultarActionPerformed
        ConsultarCliente consulCli = new ConsultarCliente();
        jDesktopPane1.add(consulCli);
        consulCli.setVisible(true);
    }//GEN-LAST:event_menuClientesConsultarActionPerformed

    private void menuPedidosAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidosAdicionarActionPerformed
        AdicionarPedido adc = new AdicionarPedido();
        jDesktopPane1.add(adc);
        adc.setVisible(true);
    }//GEN-LAST:event_menuPedidosAdicionarActionPerformed

    private void menuFuncionariosAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionariosAddActionPerformed
        AdicionarFuncionario adcFun = new AdicionarFuncionario();
        jDesktopPane1.add(adcFun);
        adcFun.setVisible(true);
    }//GEN-LAST:event_menuFuncionariosAddActionPerformed

    private void menuDptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDptActionPerformed
     Departamentos dept = new Departamentos();
     jDesktopPane1.add(dept);
     dept.setVisible(true);
    }//GEN-LAST:event_menuDptActionPerformed

    private void menuFuncionariosDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionariosDeleteActionPerformed
        DeletarFuncionario func = new DeletarFuncionario();
     jDesktopPane1.add(func);
     func.setVisible(true);
    }//GEN-LAST:event_menuFuncionariosDeleteActionPerformed

    private void menuFuncionarioUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionarioUpdateActionPerformed
     AtualizarFuncionario atua = new AtualizarFuncionario();
     jDesktopPane1.add(atua);
     atua.setVisible(true);
    }//GEN-LAST:event_menuFuncionarioUpdateActionPerformed

    private void menuHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHorariosActionPerformed
        Horarios hora = new Horarios();
        jDesktopPane1.add(hora);
        hora.setVisible(true);
    }//GEN-LAST:event_menuHorariosActionPerformed

    private void menuCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCaixaActionPerformed
        Caixa cxa = new Caixa();
        jDesktopPane1.add(cxa);
        cxa.setVisible(true);
    }//GEN-LAST:event_menuCaixaActionPerformed

    private void menuPedidosAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedidosAtualizarActionPerformed
        AtualizarFuncionario atuFun = new AtualizarFuncionario();
        jDesktopPane1.add(atuFun);
        atuFun.setVisible(true);
    }//GEN-LAST:event_menuPedidosAtualizarActionPerformed

    private void AdicionarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarProdActionPerformed
        AdicionarProduto addProd = new AdicionarProduto();
        jDesktopPane1.add(addProd);
        addProd.setVisible(true);
    }//GEN-LAST:event_AdicionarProdActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ConsultarProduto consultProd = new ConsultarProduto();
        jDesktopPane1.add(consultProd);
        consultProd.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuFuncionariosSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionariosSearchActionPerformed
        ConsultarFuncionario consultFunc = new ConsultarFuncionario();
        jDesktopPane1.add(consultFunc);
        consultFunc.setVisible(true);
    }//GEN-LAST:event_menuFuncionariosSearchActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        DeletarProduto delProd = new DeletarProduto();
        jDesktopPane1.add(delProd);
        delProd.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gerentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AdicionarProd;
    private javax.swing.JMenu JCaixa;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem menuCaixa;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenuItem menuClientesAdicionar;
    private javax.swing.JMenuItem menuClientesAtualizar;
    private javax.swing.JMenuItem menuClientesConsultar;
    private javax.swing.JMenuItem menuClientesDeletar;
    private javax.swing.JMenuItem menuDpt;
    private javax.swing.JMenuItem menuEntrega;
    private javax.swing.JMenuItem menuFuncionarioUpdate;
    private javax.swing.JMenuItem menuFuncionariosAdd;
    private javax.swing.JMenuItem menuFuncionariosDelete;
    private javax.swing.JMenuItem menuFuncionariosSearch;
    private javax.swing.JMenuItem menuHorarios;
    private javax.swing.JMenuItem menuPedidosAdicionar;
    private javax.swing.JMenuItem menuPedidosAtualizar;
    private javax.swing.JMenuItem menuPedidosConsultar;
    private javax.swing.JMenuItem menuPedidosDeletar;
    // End of variables declaration//GEN-END:variables
}
